### PR TITLE
Use absolute path of grab2.py for the kitten call

### PR DESCRIPTION
**Pull request by Sighery**
There's a bit more technical info on the commit message body itself.

To explain, my current usecase is that I have my kitty conf setup this way:
```
$ tree -l ~/.config/kitty/
~/.config/kitty/
├── kittens
│   └── kitty_grab -> ~/Programming/dotfiles/dotfiles/kitty-kittens/kitty_grab
│       ├── grab2.py
│       ├── grab.conf.example
│       ├── kitty.conf.example
│       ├── LICENSE
│       ├── __pycache__
│       │   ├── grab1.cpython-38.pyc
│       │   └── grab2.cpython-38.pyc
│       └── README.md
├── kitty.conf -> ~/Programming/dotfiles/dotfiles/config/kitty/kitty.conf
└── themes
    ├── 3024_Day.conf -> ~/Programming/dotfiles/dotfiles/kitty-themes/themes/3024_Day.conf
    ├── Afterglow.conf -> ~/Programming/dotfiles/dotfiles/kitty-themes/themes/Afterglow.conf
    └── Zenburn.conf -> ~/Programming/dotfiles/dotfiles/kitty-themes/themes/Zenburn.conf
```
All the symlink directions are irrelevant, it's simply how I set up most of my dotfiles, but it makes no difference whatsoever to this PR if it was all hard copies or just symbolic links.

Now, for the sake of namespaces and not having conflicting kittens, I like to keep them all under the `kittens` directory, and each one has its own "package" directory there.

However, I then had an issue trying to run this kitten. On `grab1.py`, (I assume, I'm just now getting into kitty and haven't even gone through the configuration fully yet) spawn a new kitten by pointing it to the grab2.py file. However this has an issue, which is that it requires both files to be in the directory from which kitty spawns new kittens so it is a valid path name. This directory seems to be `~/.config/kitty/`.

This can be easily solved with a few minimal changes, though. Since kittens are Python packages, we can make use of Python's import to import `grab2.py` from `grab1.py`, so no matter where `grab1.py` might be called from, it will know the path to its package directory, and it will be able to find any other Python files in its package, in this case, `grab2.py`. And second, we can use the `__file__` attribute of the `grab2` module to figure out its relative path to the package, and then `os.path.abspath` to figure out the module's absolute path in the system, which is ultimately what Kitty will need to spawn the new kitten.

### CODE REVIEW

**Comment by yurikhan** [comment]
This is a neat trick. Thank you. I’ll try it out over the weekend and maybe even rename the stages to make it more obvious which one to bind.

**Comment by yurikhan** [comment]
Looking into it more closely:

* The repository name I chose, `kitty-grab`, is unfortunate, because Kitty replaces all hyphens with underscores when loading a kitten. I presume this is why you clone it as `kitty_grab` and name your symlink `kitty_grab` as well.
  * I think I should rename the repository to `kitty_grab`, and stick to this naming convention for any other kittens I make.
* The import trick works if you have a full clone of the kitten repository in your .config/kitty, or a directory symlink to a full clone. It does not work if you have a file symlink to only `grab1.py`.
  * Probably, the latter case is not so important, as long as I document the preferred installation method.
* I do not see what `abspath` brings to the table. For me, `grab2.__file__` is already an absolute path. However, it does not hurt anything.

**Comment by Sighery** [comment]
You're right. Added some code to keep the previous behaviour as a fallback. It will try to import a module `grab2` and use it's `__file__` for the invocation. But if either the import, or the attribute doesn't exist, maybe because there's some funky file hierarchy going on, it will just fallback into the previous behaviour of looking for `grab2.py` on the execution directory.

Also removed the `abspath` since as you said it's not needed, and it seems to work without it so fine by me.

And yes, Kitty does replace hyphens by underscores. Although really that's just a Python thing. Defined here in [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names), package and modules might only contain lowercase and underscores.

**Comment by yurikhan** [comment]
Yes, names of packages and modules must not contain hyphens; but the way things are right now, `grab1.py` and `grab2.py` are two unrelated modules not contained in any package. A package would have an `__init__.py` file. And there is, theoretically, no reason why a Python module cannot reside in a directory containing hyphens, whitespace, dots, or any other characters not valid in identifiers.

I get the impression that the kitten system is not yet mature; as a community, we don’t yet know what is good.

**Comment by Sighery** [comment]
Yes, and no. I'm not an expert, I haven't dealt much with creating and uploading Python packages, but:

Your Python modules do probably reside in a directory containing hyphens. In Linux, it's probably `/usr/lib/python3.8/site-packages/`. If you're using virtualenv then it's gonna be almost the same path but inside the virtualenv directory you create.

The reason why it works is that `site-packages` is not a Python module or anything. It's simply a path Python knows where to search for packages/modules. You can check all these paths by doing `sys.path` after importing `sys`.

On a valid Python package you'll probably have a structure like:
```
example-package/
├── example
│   ├── __init__.py
│   └── magic.py
└── setup.py
```

Now, when uploading to PYPI or maybe a private registry, I believe it will use the variable `name` for the name of the package in the registry. And when installed into your system, it won't actually save your whole file structure, but instead will only install the `example` directory inside your `site-packages` path, which will be a valid Python module name.

You can test this with `virtualenv` and the `scikit-learn` package (on Linux, at least):
```bash
virtualenv venv
source venv/bin/activate
pip install scikit-learn
ls venv/lib/python*/site-packages/
```

There you'll see there's a new directory called `sklearn`. If you go into the [scikit-learn repository](https://github.com/scikit-learn/scikit-learn) you'll see it follows the same structure as my example up there (although, you know, more complex with more files). It has a `setup.py` that contains `name` equal to `scikit-learn`, and a directory next to it called `sklearn`, which will be the new Python module that will be installed, and you can see it on the last `ls` command from the test above.

So yes and no. Your Python module with no hyphens can live in a directory with those characters, but unless you add that path to your `sys.path`, Python won't look in there so it won't be imported.

---

All this aside, I wouldn't recommend making this repository a valid Python package. As you mention, the whole kitten system is not yet mature and this (at least for now) works. And doesn't seem like Kitty requires nor plans to require valid Python packages for the kittens. And they can go a lot of different ways to standardise kittens, so I belive it's not worth the investment.

So yeah, don't worry about it. Your current installation instructions (with my latest commit) will still work. People like me that want to have a different structure that is (at least currently) non-standard, can just figure out how to do it by ourselves.

**Comment by yurikhan** [comment]
OK, here’s what I think.

The only new installation scheme that becomes possible when we put `import grab2` under a `try`/`except` is:

```
.config/kitty
    grab2.py
    some/path/grab1.py
```
…where grab1.py, grab2.py, and any of the directories on the path to grab1.py may or may not be symlinks. This does not look like a sane configuration to me.

So I’m taking the previous version of this pull request, minus the `abspath`, renaming the repo so that `git clone git@github.com:yurikhan/kitty_grab.git` does the right thing, and documenting that as the preferred installation method. Also, I will raise an issue to get an explanation why Kitty needs that hyphen-to-underscore replacement and maybe if it could be dropped or made more specific.

**Comment by yurikhan** [comment]
Merged manually.

**Pull request closed without merging**
